name: CI

on:
  push:
    branches: [main]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    strategy:
      matrix:
        zig-version: [0.15.1]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
      - name: Build docs
        if: github.ref == 'refs/heads/main'
        run: zig build docs
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/docs/zonBuild

  publish-docs:
    needs: [build-docs]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
